
name: 'ambergrid_dbt'
version: '1.0.0'

profile: 'ambergrid_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  ambergrid_dbt:
    staging:
      +schema: silver
      +materialized: view
    intermediate:
      +schema: silver
      +materialized: ephemeral
    marts:
      +schema: gold
      +materialized: table