output "snowflake_iam_user_arn" {
  value       = snowflake_storage_integration_aws.scada_telemetry_integration.describe_output[0].iam_user_arn
  description = "Snowflake-managed IAM user ARN. Use as the Principal in the trust policy of elite-snowflake-role"
}

output "snowflake_external_id" {
  value       = snowflake_storage_integration_aws.scada_telemetry_integration.describe_output[0].external_id
  description = "External ID generated by Snowflake. Use as the sts:ExternalId condition in the same trust policy"
}
